### ISSUE TITLE
Unknown blueprint: ember-electron

### ISSUE THREAD

**Issue by jaykilleen** [felixrieseberg/ember-electron#106]
Hi,

Very noobish question here. I have a new Electron app that I have built and want to use ember-electron.

I have followed your steps on the README.md 

I could not run `ember install ember-electron` as I was thrown the error `node_modules appears empty, you may need to run`npm install``

Tried instead `npm install ember-electron` which works. Then `ember g ember-electron` but it has thrown the error `"Unknown blueprint: ember-electron"`. 

I know you mention `please ensure (⚠️) that the blueprint generation runs`. How do I ensure this? I've googled this error and get 0 results... 🎱 :/

Sorry, I am just figuring this one out from a Rails background and have never done desktop app development, electron or ember.

Any guidance or hints would be appreciated or I'll report back here if I figure it out.

**Comment by d-schloss-mvg** [comment]
Did you create an Ember-project before via `ember init` ?

**Comment by felixrieseberg** [comment]
Hey @jaykilleen - no worries, we can get this done. Ember uses your `package.json` to figure out which addons are installed, so I'd recommend that you either install with `ember install ember-electron` (which will run the blueprint for you) or install with `npm install ember-electron --save-dev` followed by `ember g ember-electron`.

I'd recommend that you give ember a quick go without ember-electron (just for a minute) - once you have the ember app running you will have confidence that all your trouble that follows is truly my fault. 

I'm closing the issue since I'm pretty confident that this isn't an actual bug, we can always circle back if it  is 👍 On that note, thank you so much for giving it a try!

**Comment by yefengbar** [comment]
tanks for @felixrieseberg it`s work in my object `npm install ember-electron --save-dev`
