### ISSUE TITLE
Leaks package.json

### ISSUE THREAD

**Issue by DuBistKomisch** [felixrieseberg/ember-electron#136]
I noticed this addon just copies your ember app's `package.json` into the packaged app. From what I understand, electron only needs `name`, `version` and `main`, so shouldn't `ember-electron` construct a new `package.json` with just those three fields copied from the main one?

Currently it leaks all sorts of stuff, most importantly signing settings for windows and mac, and every dependency, and basically just a bunch of things you wouldn't want your users to see.

The only current way around this I found is to create a separate `electron/package.json`, but it has to be manually copied into the build directory since `copy-files` always preserves the relative path.

**Comment by malept** [comment]
If a user's going to root around in your app, they're going to eventually find every dependency anyway, since all of the production dependencies are bundled.

@anulman perhaps with #129, you can default to putting all of the forge config into a separate JS file and then ignore said file in the Electron Packager config.

**Comment by anulman** [comment]
@DuBistKomisch—[upstream work in Forge](https://github.com/electron-userland/electron-forge/pull/134/files) (thanks @malept @MarshallOfSound) will land this automatically with #129
