### ISSUE TITLE
How to access my ember-app's service

### ISSUE THREAD

**Issue by Zorig** [felixrieseberg/ember-electron#137]
First of all, thank you so much for making awesome application. I am trying to make media keys available to my ember-app. When i press mediakey(pause/play) it should call function in `ember-app/service/play.js` how can i do it? @felixrieseberg

**Comment by pichfl** [comment]
Sites like Stackoverflow would be a more appropriate place to ask this type of question as issue trackers should only be used for their namesake. 

However, to point you and anyone searching for this in the right direction:
What you are asking for is inter process communication between your host/main application (electron) and the client application (Ember). This can be done quite easily in electron using [ipcMain](http://electron.atom.io/docs/api/ipc-main/) and [ipcRenderer](http://electron.atom.io/docs/api/ipc-renderer/). 

Your main application is allowed to register for global shortcuts, so called accelerators using the [globalShortcut](http://electron.atom.io/docs/api/global-shortcut/) API. 

Once your shortcut is registered you can use it's callback to send an IPC message using the send method of your mainWindow.webContents. See [webContents.send](http://electron.atom.io/docs/api/web-contents/#contentssendchannel-arg1-arg2-) for details.

In your Ember service use `requireNode` to require the ipcRenderer and use it's `on` method to listen for incoming IPC messages. Since IPC messages can contain any number of arguments, you can send along the pressed key and use that information in your callback to trigger stuff in your ember application.

My personal suggestion is to register for the ipcRenderer stuff in the init() method of an Ember service.

**Comment by Zorig** [comment]
@pichfl  thanks for reply and pointing me out, i registed mediakeys using `globalShortcut.register` method in `electron.js` and now i added playpause key like this: 
```javascript
const ipcMain = electron.ipcMain;
const globalShortcut = electron.globalShortcut;
globalShortcut.register('MediaPlayPause', () => {
        ipcMain.on('asynchronous-message', (event, arg) => {
            console.log(arg) // prints "ping"
            event.sender.send('asynchronous-reply', 'pong')
        });

        ipcMain.on('synchronous-message', (event, arg) => {
            console.log(arg) // prints "ping"
            event.returnValue = 'pong'
        });
        console.log('HELLO');
        mainWindow.webContents.send('ping', 'whoooooooh!');
    });
```
and on my service in emberapp i put these:
```javascript
import Ember from 'ember';
import moment from 'moment';
const ipcRenderer = requireNode('electron');

export default Ember.Service.extend({
    play(source, track) {
        console.log(ipcRenderer.sendSync('synchronous-message', 'ping')); // prints "pong"
        ipcRenderer.on('asynchronous-reply', (event, arg) => {
            console.log(arg); // prints "pong"
        });
        ipcRenderer.send('asynchronous-message', 'ping');
    },
```
Still no sign of console.log()
But i don't understand how to send it to my service. Am i doing it wrong?

**Comment by pichfl** [comment]
```
const ipcRenderer = requireNode('electron');
```

should be 

```
const { ipcRenderer } = requireNode('electron');
```

and it should throw errors otherwise.

**Comment by Zorig** [comment]
:+1: oh i put `ipcRenderer.on` function in service's `init` method and just now it solved i think
