### ISSUE TITLE
:package failing due to missing pseudomap

### ISSUE THREAD

**Issue by anulman** [felixrieseberg/ember-electron#167]
_n.b. description is rough; just trying to jot this down & will come clean up shortly_

Was trying to package https://github.com/makepanic/ember-hearth/tree/ember-hearth-39 with @locks and @makepanic, and we are getting errors re: pseudomap not being available.

When inspecting `ember-electron/out/.../node_modules/lru-cache/package.json` (dep of electron-compile that depends on pseudomap), it became clear lru-cache is not installing its deps correctly. The package.json deps object is empty, while `_dependencies` includes the expected values.

Current hypothesis is that this is related to ember-hearth's dep on `npm`, at a different version than is required by `npmi` (ember-electron dep).

We should solve this by emberconf

**Comment by makepanic** [comment]
A quick update:
- it's probably related to `ember-cli` being a dependency
- if i create a clean ember-electron@2 project with all hearth dependencies except `ember-cli`, it packages and runs without issues. As soon as `ember-cli` is added it fails with the `Error: Cannot find module 'pseudomap'` error

**Comment by anulman** [comment]
@makepanic interesting. How / why does ember-hearth consume e-cli? Based on a quick read through the code, I couldn't find any requires / where it gets invoked

**Comment by makepanic** [comment]
`ember-cli` is only used as a dependency to call ember commands from within the ui.
I.e. to create a new ember project it uses the dependency and [runs `ember init`](https://github.com/ember-learn/ember-hearth/blob/master/cli/hearth.js#L93)

In other places we could probably get around not using cli as a dependency, because it only tries to run commands in existing ember projects, i.e. to [get the list of commands](https://github.com/ember-learn/ember-hearth/blob/master/app/routes/project/detail.js#L37-L44).

**Comment by anulman** [comment]
Per Slack, @makepanic was able to circumvent this error by adding the following as dependencies downstream:

```
+    "async": "^2.1.5",
+    "balanced-match": "^0.4.2",
     "bluebird": "^3.4.7",
+    "concat-map": "0.0.1",
     "electron-compile": "^6.1.2",
     "ember-cli": "^2.11.1",
     "got": "^6.7.1",
     "jsonapi-serializer": "^3.4.2",
     "jsonminify": "^0.4.1",
     "mkdirp": "^0.5.1",
+    "ms": "^0.7.3",
     "nedb": "^1.8.0",
     "node-dir": "^0.1.16",
     "npm": "^4.3.0",
+    "pseudomap": "^1.0.2",
     "semver": "^5.3.0",
     "tar": "^2.2.1",
     "temp": "^0.8.3",
-    "uuid": "^3.0.1"
+    "underscore": "^1.8.3",
+    "uuid": "^3.0.1",
+    "wrappy": "^1.0.2",
+    "yallist": "^2.0.0"
```

@makepanic can you share more about how you discovered these, so we can investigate the pattern further? The deps install code definitely changed from 1.x to 2.x, but not in ways that would cause the behavior @locks and I observed. Curious to investigate

**Comment by makepanic** [comment]
I basically ran `ember electron:package --platform=linux --arch=x64`, waited a while for the build to finish and then tried to run hearth (`./ember-electron/out/ember-hearth-linux-x64/ember-hearth`).

It would print something like:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'pseudomap'
```

And i installed pseudomap as dependency (`npm i --save pseudomap`).
After doing it again i got a different missing module which i installed and so on.

Now the issue is that the SRI hash mismatches 😭

**Comment by anulman** [comment]
@makepanic have you resolved the SRI hash issue? IIRC that's related to a missing .compilerc.

Grab me in-channel if that's still the case, otherwise closing for now as this was related to deps not installing their own deps properly.
