### ISSUE TITLE
Beta: Output in /dist no longer lines up with default output

### ISSUE THREAD

**Issue by pichfl** [felixrieseberg/ember-electron#177]
In our latest iteration the output in `/dist` is now quite different for `ember electron` than it is for `ember build`, which might lead to some confusion, especially in projects that are not exclusively using with Electron. 

This might be a non-issue, but I had to note this down somewhere.

**Comment by jacobq** [comment]
This was mentioned during the [copy-files discussion](https://github.com/felixrieseberg/ember-electron/issues/123#issuecomment-285481050), and I think it definitely deserves mentioning in the docs. Fortunately, a quick glance at the contents of `dist` reveals an `ember` folder which has the expected structure, so I don't think it's going to cause too much pain.

**Comment by anulman** [comment]
I agree this is an issue. My preference would be to build to a separate dir (e.g. `ember`, `electron-dist`) in the root dir, and clean up on completion of those commands.

**Comment by bendemboski** [comment]
We could just add `electron-dist` to `.npmignore` and change the default [here](https://github.com/felixrieseberg/ember-electron/blob/master/lib/commands/build.js#L40) if we think this is going to cause confusion, but I would expect anybody running an `ember-electron` app will know enough to not be surprised to find the electron app in `dist` instead of their ember app files.

**Comment by anulman** [comment]
My concern is not with "surprise to find it in their files" and instead with publishing scripts meant to push dist to remote hosts. I don't feel comfortable leaving these artifacts around.

**Comment by bendemboski** [comment]
Okay, as I said, the fix should be really easy.

**Comment by pichfl** [comment]
This is gone now that #188 is merged. Closing.
