### ISSUE TITLE
Error: Could not detect abi for version 1.6.2 and runtime electron

### ISSUE THREAD

**Issue by papakay** [felixrieseberg/ember-electron#195]
Please i'm experiencing this issue when running `ember electron:package` or `ember electron:ship`

Please how can i resolve this issue.

Thank you.

**Comment by jacobq** [comment]
@papakay Could you please provide some more context regarding your problem? Otherwise there's not much we can do to help. For example, what version of node are using, what operating system are you running, which version of `ember-cli` and `ember-electron` are you using, etc. (We're currently working on some major changes and anticipating a version 2.0 release in the next month.)

Also, if you're able, I think it'd be easier to resolve this via chat. C'mon over to the `#e-electron` channel of the [EmberJS Slack team](https://ember-community-slackin.herokuapp.com/) ([more info](http://emberjs.com/community/)).

**Comment by papakay** [comment]
@jacobq thanks immensely for this directive.

I'm using Node v7.5.0 on mac Osx (mac os sierra), 
"ember-cli": "2.10.0", 
"ember-electron": "^1.12.7",
"electron": "^1.6.2",

I was trying to build for windows X64. I have mono and wine installed as well.

**Comment by papakay** [comment]
I was able to resolve this issue by deleting my node_modules folder, bower folders and then ran npm install and bower install.

@anulman  and @jacobq thank you for your immense support and directives in getting this resolved.
