### ISSUE TITLE
protocolServe breaking uploads after upgrade.

### ISSUE THREAD

**Issue by xn** [felixrieseberg/ember-electron#228]
I just recently upgraded to 2.0.1 from version 1 and it has changed the protocol requesting files from `file://some-path` to `serve://dist/some-path`. Checking the network tab, the uploads are now end up in a state of `stalled`. First, is this protocol change desired? If so, where can I find some documentation to resolve this or is this a bug?

Thanks.

**Comment by bendemboski** [comment]
Can you provide some more information? Does it look like a CORS issue? Where are you trying to upload to, and how?

The [serve protocol](https://github.com/pichfl/electron-protocol-serve) allows to serve the Ember app from the filesystem, but using the web server semantics that Ember expects, e.g. so we can use the history location type instead of the hash location type, and so we can use absolute paths for resources rather than relative.

It is enabled from code generated from the blueprint, so you can disable it if you need to, but that would get you kinda off the beaten path, so I'd encourage you to try to debug your issue before looking into disabling the serve protocol.

**Comment by xn** [comment]
Alright, so I think I understand what is going on. The file gets "uploaded" (it's a local file and we keep it in place) and what we do is create an `Image()` object and set some properties when the `onload` event fires. This never happens because the request is `stalled`. Looking at electron-protocol-serve it seems you need to whitelist directories, but we have a situation where we will never know where those files will be held a priori.

**Comment by bendemboski** [comment]
What request is stalled? A POST request? GET?

**Comment by xn** [comment]
Get

**Comment by pichfl** [comment]
I have to mention that the protocol was not tested for this yet.

**Comment by xn** [comment]
This is not a CORS issue.

**Comment by bendemboski** [comment]
And what is the URL of the GET request?

**Comment by xn** [comment]
in version 1: `file://Users/xn/Desktop/img.png`
in version 2: `serve://dist/Users/xn/Desktop/img.png`

**Comment by bendemboski** [comment]
I see -- you're using an absolute path in the GET request. Can you use a full `file:` URI? So that when you set the image source, instead of `/Users/xn/Desktop/img.png` it's `file:/Users/xn/Desktop/img.png`?

**Comment by xn** [comment]
will test.

**Comment by xn** [comment]
Alright, now I am getting Status: `blocked:other`

**Comment by xn** [comment]
Not allowed to load local resource. Yeah, let me fix that.

**Comment by xn** [comment]
Murr. Chrome is balking. If I explicitly use the file protocol, chrome disallows that, but if I keep it blank, it adds it itself and thinks it's ok. :/

**Comment by pichfl** [comment]
I just updated the [FAQ](https://github.com/felixrieseberg/ember-electron/blob/master/docs/faq/faq.md) with a few more details on this issue.

May I suggest using a FileReader to access the local file?

**Comment by xn** [comment]
Just to see, I opened up the web permissions and the request went through, however chrome was still stopping it. I think we're going to convert it to base64 and handle it that way in the short term. Thanks for all the help and the quick responses. It is much appreciated. This is a great project. Thanks, we can close this.
