### ISSUE TITLE
Code editor does not work perfec...

### ISSUE THREAD

**Issue by mirshahreza** [felixrieseberg/ember-electron#245]
I use the Monaco in a web application with this libraries  and the bootstrap is v4 alfa 6

    <link href="~/assets/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />

    <link href="~/assets/lib/ix/ix-common.css" rel="stylesheet" />
    <link href="~/assets/lib/ix/ix-common-rtl.css" rel="stylesheet" />

    <script src="~/assets/lib/jquery/jquery-3.1.1.min.js"></script>
    <script src="~/assets/lib/jquery/jquery.extentions.js"></script>
    <script src="~/assets/lib/bootstrap/js/bootstrap.min.js"></script>

    <script src="~/assets/lib/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
    <link href="~/assets/lib/jquery-ui-1.12.1.custom/jquery-ui.min.css" rel="stylesheet" />

    <script src="~/assets/lib/JSON-Tree-Viewer/jquery.json-view.min.js"></script>
    <link href="~/assets/lib/JSON-Tree-Viewer/jquery.json-view.min.css" rel="stylesheet" />

    <script src="~/assets/lib/moment/moment.js"></script>
    <script src="~/assets/lib/moment/moment-jalaali.js"></script>

    <script src="~/assets/lib/twbs-pagination/jquery.twbsPagination.min.js"></script>
    <script src="~/assets/lib/ix/ix-auto-direct.js"></script>
    <script src="~/assets/lib/ix/ix-to-validate.js"></script>

    <script src="~/assets/lib/vue/vue.min.js"></script>
    <script src="~/assets/lib/lodash/lodash.min.js"></script>

the issue is that when I click on the code ,code editor does not work but when I click on the empty area of code editor ( editor body where there is no line of codes ) it works!!!

**Comment by pichfl** [comment]
Nothing in this issue indicates you are using Ember-Electron. If you have trouble with Microsofts monaco-editor, it might be sensible to ask your question [there.](https://github.com/Microsoft/monaco-editor/issues) 

Otherwise, linking assets from your user folder (which is indicated by the tilde `~/` in each `src`) is neither testet nor recommended and will lead to unexpected behaviour at best.

If you have issues with Ember-Electron, please specify your platform and versions of all tools involved (Ember-CLI, Ember-Electron, Electron, Monaco Editor).
