### ISSUE TITLE
how to package app to all platforms from mac os x using electron packager

### ISSUE THREAD

**Issue by Zorig** [felixrieseberg/ember-electron#302]
Hi, i have been using ember-electron and try to package app to all 3 platforms(mac osx, windows, linux) and electron-forge said it is currently only support it's own host machine OS. And it seems it does. So i searched and find electron packager, how can i using it ??? is it the electron-out/project folder? @felixrieseberg @bendemboski

**Comment by bendemboski** [comment]
@Zorig first of all, standard disclaimer that the current recommended approach is to build each platform natively rather than cross-compiling. However, if you want to try anyway, it is supported by `electron-forge` and `ember-electron` as long as you don't have any native modules. You just need to run `ember electron:package --platform win32` or `ember electron:package --platform linux` (same with `ember electron:make` if you want to build installers).

However, to cross-compile a windows package you'll need to have `wine` and `mono` installed.
