### ISSUE TITLE
Debug server should be started in a packaged electron build if env is development

### ISSUE THREAD

**Issue by nselikoff** [felixrieseberg/ember-electron#33]
I see there's an option to specify environment when packaging a build (e.g. `ember electron:package -dev` but if I package a dev build, the debug server isn't started.

I assume it's as easy as using some of the code from the electron.js command in the package.js command? https://github.com/felixrieseberg/ember-electron/blob/0327d570139765aa76fc6e95de9a8c9dd04df58a/lib/commands/electron.js#L57-L60

**Comment by kdawgwilk** [comment]
Also trying to figure out if its possible to run other environments such as staging/qa/etc.  Is there a way to pass those to ember-electron?

**Comment by kdawgwilk** [comment]
Ah just saw this PR #27

**Comment by anulman** [comment]
So, looked into this, and there are some user ergonomics to consider, as the debug server started by `ember electron` tightly couples its lifecycle to the command itself (i.e. starts in the command & cleans itself up at `process.on('SIGTERM')`).

To implement this, we'd need to ship at least one add'l command to start / stop the server at will, since packaged builds are not guaranteed to be opened while the debug server is alive.

Is this still a feature we want in the lib? This is not something I'd be able to address soon, but can probably talk / walk through someone through the steps necessary who's got a burning desire to see it land 👍

**Comment by nselikoff** [comment]
Thanks for following up on this. I wouldn't describe this as a burning desire, so I'll close it :)
