### ISSUE TITLE
Use electron-builder under the hood instead of electron-packager

### ISSUE THREAD

**Issue by develar** [felixrieseberg/ember-electron#62]
Otherwise users forced to solve "How to create installers?" issue :) And it leads to https://github.com/electron/windows-installer/issues/81

I am not familiar with ember-electron, just ask what do you think. As electron-builder maintainer I will do anything on electron-builder side that will be required for better integration.

**Comment by felixrieseberg** [comment]
Ohhh, I'd actually be a big fan of that. We simply got started over here before your package came around, but if possible, I'd love to have it.

Would you consider helping out with a PR?

**Comment by develar** [comment]
>  I'd actually be a big fan of that. 
> Would you consider helping out with a PR?

Great. So, I will investigate and propose/open PR.

**Comment by locks** [comment]
@develar poke, did you manage to integrate it?

**Comment by develar** [comment]
@locks Not yet, quite busy :( Should be easy, though.

**Comment by Polve** [comment]
This seems necessary to use the auto-update feature of electron, is there any news and/or workarounds?

**Comment by felixrieseberg** [comment]
Nah, not necessary at all. I'm using `ember-electron` to build Ghost Desktop (which auto-updates just fine). You can check it out here: https://github.com/tryghost/ghost-desktop

That said, I'd still ❤️ a PR that puts in electron-builder. Its API isn't the best, but it handles a ton of stuff on top of electron-packager.

**Comment by natebeck** [comment]
I actually just wrapped up a project using electron-builder.  One of the huge benefits of electron-builder is you can use TravisCI or CircleCI to build both Mac and Windows versions of the application.  This is important for projects that use are private, since TravisCI and AppVeyor can fairly expensive for private repos.

We were able to successfully follow the instructions listed here: http://electron.rocks/electron-builder-explained/

I'll take a stab at looking into this as I go along.

**Comment by locks** [comment]
@natebeck 🙏

**Comment by develar** [comment]
> Its API isn't the easiest to integrate

Any suggestion/complains are welcome and will be addressed.

Currently, I don't have time to prepare PR but I can help anyone (including required changes on electorn-builder side) who want to work on this.

**Comment by anulman** [comment]
@felixrieseberg can we close this, in favour of the work going in #129 ?

**Comment by natebeck** [comment]
Oh yeah, using electron-forge makes a lot of sense. Closing this one makes sense.

**Comment by gossi** [comment]
What's the benefit of electron-forge over electron-builder?

**Comment by felixrieseberg** [comment]
Think of electron-forge as a more complete implementation of "everything related to running an Electron app" - and implementing it is a lot easier. In detail, the good folks over in the electron-forge repo have been helping us (aka @anulman, who's doing all the work) really out.

I'm closing this - not because I don't <3 electron-builder, but because the electron-forge work is so far along.

**Comment by develar** [comment]
@natebeck Could you please provide details how did you wrap? https://github.com/electron-userland/electron-builder/issues/1273 Or do you wait when electron-builder will be supported in the ember-electron? Users can use electron-builder to pack result of electron-packager, but still have to solve code signing, asar, package.json data stripping and so on manually. And that's not good.

@felixrieseberg It seems #129 will be merged soon? In this case it will be easy to just plug-in electron-builder into the electron-forge :)

**Comment by anulman** [comment]
@develar #129 should be merging very soon. Plan is to cut an alpha / beta build shortly, but it can be used today for `electron`, `electron:package`, and `electron:make` commands (with a bit of config necessary as we wait for upstream merges).

Lmk if in a rush and I can help you get set up. Else closing this issue now in favor of tracking there
