### ISSUE TITLE
Cannot require ipcRenderer

### ISSUE THREAD

**Issue by ColtonProvias** [felixrieseberg/ember-electron#9]
I need to include ipcRenderer in my ember code.  Unfortunately, this:

```js
const ipcRenderer = require('electron').ipcRenderer;
```

returns `undefined`.

**Comment by felixrieseberg** [comment]
Thanks for reporting! Have you confirmed that it works when you don't use ember-electron? It'd be super surprising if ember electron was really the issue here, given that the addon just pipes things through - we don't change anything about your Ember code or Electron itself.

**Comment by ColtonProvias** [comment]
Looking into it, it appears that it's coming from the loader in ember-cli/Ember that overrides the require function needed by Electron.  The issue can't be fixed by providing assigning Electron's require to another name; Electron expects it to be named require.

**Comment by felixrieseberg** [comment]
Oh sorry, that is a blatant case of me not documenting things well enough - you can call Node's require function from within Ember using `requireNode()`. 

This should fix your issue, but I'l leave this issue open until I got around to properly documenting it in the readme (probably tomorrow).

**Comment by ColtonProvias** [comment]
`requireNode()` does not fix this issue either as it is just a reassignment, which I stated earlier doesn't work.  Electron expects it to be named `require`, not anything else, strangely.

**Comment by felixrieseberg** [comment]
I've dabbled with the Electron code base (there's some of my C++ in there) - and I'm fairly sure that your issue is not with ember-electron. You *can* have issues if Ember Cli is overwriting `
require`, but if you're just using the addon as-is, it should take care of that.

I'd love to help you though. Do me a quick favor - fire up Electron by itself and run the code you're trying to run in there - if that works, I'd be super surprised. I cannot reproduce your issue - a repro zip (or something like that) would be awesome.

**Comment by felixrieseberg** [comment]
Just to help you debug: I attached a blank app that does nothing but requiring and logging both electron and the ipcRenderer.

[testapp.zip](https://github.com/felixrieseberg/ember-electron/files/66333/testapp.zip)
